# Yarn v4 Configuration 🧶
# Using node-modules linker for compatibility with Vite and other tools
nodeLinker: node-modules

# Cache configuration
enableGlobalCache: false
enableMirror: false

# Telemetry (disabled for privacy)
enableTelemetry: false

# Compression level: mixed (good balance of speed and size)
compressionLevel: mixed

# Network settings
httpTimeout: 60000
networkConcurrency: 16

# Logging
logFilters:
  - code: YN0013
    level: discard
